version: '3'
services:
  csi:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /home
    volumes:
      - ./home:/home
      - ./footprint:/footprint
      - ./dataset:/dataset
      - ./cache:/cache
  elasticsearch:
    user: "${UID}:${GID}"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
       - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    user: "${UID}:${GID}"
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - "5601:5601"
volumes:
  elasticsearch:
